language: node_js # 声明环境为node
node_js: stable
# Travis-CI Caching
cache:
  directories:
    - node_modules # 缓存node_modules文件夹
# S: Build Lifecycle
install:
  - npm install # 下载依赖
script:
  - hexo g
after_script: # 推送
  - cd ./public
  - git init
  - git config user.name "xiaxianzhi"
  - git config user.email "xxz120@gmail.com"
  - git add .
  - git commit -m "Update blog"
  - git push --force --quiet "https://${CODING_TOKEN}@${CODING_REF}" master:master # 通过之前存在Travis-CI里的token以及github仓库的地址推送到相应的master分支
# E: Build LifeCycle
branches:
  only:
    - master # 只对hexo分支构建
